name: publish

on:
  release:
    types: [published]

jobs:
  publish:

    runs-on: ubuntu-18.04

    timeout-minutes:
      10

    steps:
    - uses: actions/checkout@master
      with:
        token: ${{ secrets.GH_ACTION_REPOS_TOKEN }}
        # "ref" specifies the branch to check out.
        # "github.event.release.target_commitish" is a global variable and specifies the branch the release targeted
        ref: ${{ github.event.release.target_commitish }}

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12

    - name: setup
      env:
        NPM_TOKEN_GITHUB: ${{ secrets.NPM_TOKEN_GITHUB }}
      run: |
        echo "//npm.pkg.github.com/:_authToken=${NPM_TOKEN_GITHUB}" > $HOME/.npmrc
        git config --global user.name "racconbot"

    - name: install dependencies
      run: |
        npm install

    - name: build packages
      run: |
        npm run build:prod

    - name: bump npm version
      run: |
        npm version ${{ github.event.release.tag_name }}

    - name: publish
      run: |
        npm publish

    - name: push updates
      run: git push
      env:
        github-token: ${{ secrets.GH_ACTION_REPOS_TOKEN }}
